.\"                                      Hey, EMACS: -*- nroff -*-
.TH LATOP 1 "September 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
latop \- Filter the output messages of LaTeX
.SH SYNOPSIS
.B latop
.SH DESCRIPTION
.PP
\fBlatop\fP filters the output messages of LaTeX. It ignores unimportant messages and only keeps warning and errors, printed in a standardised way.

Right now, latop is only a work in progress, and should only be used by Melt.
.SH AUTHOR
Latop was written by Romain Bardou as part of the Melt distribution.
.PP
This manual page was written by Romain Bardou (but may be used by others).

